### ISSUE TITLE
Add user authentication to SDR POC UI

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#106]
- [x] Structure the authentication such that there could be plugins for multiple clouds
- [x] Implement an auth plugin for IBM Cloud (including SSO) such that only cloud users in the same account as the SDR UI is running in can view any of the pages of the UI
- [x] Also add graphql subscriptions to have the Global Keywords and Edge Nodes pages update with new data as it is written to the db

**Comment by varatep** [comment]
Met with Matthew Perrins to discuss possible alternative solutions to IAM, since we do not want the client to continuously go through the same process to get a Bluemix Plugin Developer token/API key. We will be using the App ID service in the Bluemix catalog which will allow clients to stand up their own authentication/authorization services in their own Bluemix accounts and they can whitelist users from there.

Currently working on integrating the App ID service into the SDR UI.

**Comment by varatep** [comment]
Finished up integrating `APP ID`'s authentication system into the app. Worked past an issue with the `Express` server not rendering the React app properly once the user was authenticated.

Currently working on getting the deployment on `Bluemix` to work properly. There is currently a callback issue where the deployed server on `Bluemix` does not recognize the callback route from `APP ID` inside `Express`.

**Comment by varatep** [comment]
We are not using GraphQL subscriptions to get live data since there is no event system in place in the back end right now. Instead, we are using graphql polling to re-fetch data every second.
