### ISSUE TITLE
cpu2msghub & helloworld new structure and doc updated

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/examples#139]
- [x] Add simple helloworld sample (bruce)
- [ ] Add helloworld to the registration page and the dev guide (ivan reviewing)
- [x] Change `cpu2msghub` to be structured like `helloworld` (bruce)
- [x] Change `cpu2msghub` to not use HZN_PATTERN for the msg hub topic
- [ ] Modify dev guide to give instructions for starting cpu2msghub (get msghub api key, create topic) after the helloworld sample. Remove the cpu2msghub step-by-step commands that are now in the cpu2msghub `README.md` (ivan reviewing)

Test in all 3 modes the examples are used in:
- [x] IBM Edge Fabric Developer building/publishing the example: use the default variables defined in `horizon/hzn.env`, build/hzn dev/publish/hzn register for all 3 arches and use a pattern that includes all 3.
- [x] Customer Service Developer: following dev guide, change variables in `horizon/hzn.env`, build/hzn dev/publish/hzn register for current machine's arch. (ivan testing)
- [x] Customer User: following "Registering Your Edge Machine", `hzn register` on their edge node. (ivan testing)

**Comment by jiportilla** [comment]
6.10.19 Update: Testing helloworld instructions in Dev Section, also see feedback from earlier note on typos & grammar document - https://ibm.box.com/s/5611hfmv7b0814tg23pygnhlp2af2l2o

-The "helloworld" Example Service
	-examples/edge/services/helloworld
	https://test.cloud.ibm.com/docs/services/edge-fabric?topic=edge-fabric-dev-helloworld#examples-edge-services-helloworld
	
1.
	3 Dockerfile.* variants for 3 different hardware architectures
	""three"" Dockerfile.* variants for ""three"" different hardware architectures
		
2. 
	stopping the helloworld Service:
	""hzn unregister -f""  or ""hzn dev service stop""


	-Choose Another Example
	https://test.cloud.ibm.com/docs/services/edge-fabric?topic=edge-fabric-dev-helloworld#choose-another-example


1.	
	Do we need Example 1 helloworld ?? (Reader just completed this example)
	
2.	
	supporting 3 hardware architectures
	supporting ""three"" hardware architectures
	
3.	
	services of 2 other IBM 
	services of ""two"" other IBM )

**Comment by jiportilla** [comment]
Helloworld testing feedback from Developer Section


1.
Update Open-Horizon Examples repo link from
https://github.com/open-horizon

to:
https://github.com/open-horizon/examples

2.

After Don’t type those characters.

(Does user need sudo to install git, make and jq ? )

apt install -y git make jq
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

3.
Take a look around ls -R results look different from Documentation (no ./horizon/pattern subdirectory and pattern files names are different):

$ ls -R
.:
Dockerfile.amd64  Dockerfile.arm64  README.md  service.sh
Dockerfile.arm    Makefile          horizon
./horizon:
dependencies  hzn.cfg  pattern  service.definition.json  userinput.json
./horizon/dependencies:
./horizon/pattern:
pattern-helloworld-all-arches.json  pattern-helloworld.json


Testing VM:
ls -R
.:
Dockerfile.amd64  Dockerfile.arm  Dockerfile.arm64  horizon  Makefile  README.md  service.sh

./horizon:
dependencies  hzn.json  pattern-all-arches.json  pattern.json  service.definition.json  userinput.json

./horizon/dependencies:

4.
On the README.MD file, Using the Hello World Example Edge Service section, 

4.1
add link to “Try it / Installing Horizon Software On Your Edge Machine” - https://test.cloud.ibm.com/docs/services/edge-fabric?topic=edge-fabric-adding-devices
•	First, go through the "Try It" page "Installing Horizon Software On Your Edge Machine" to set up your edge node.
4.2.
HZN_EXCHANGE_NODE_AUTH :
export HZN_EXCHANGE_NODE_AUTH="<mynodeid>:<mynodetoken>"
Should not to be confused with EXCHANGE_NODEAUTH In the Registration procedure section - https://test.cloud.ibm.com/docs/services/edge-fabric?topic=edge-fabric-registration#registration-procedure
-	# Do not edit the lines below unless instructed to do so:
-	export EXCHANGE_NODEAUTH="$HZN_DEVICE_ID:$HZN_DEVICE_TOKEN"
4.3.
hzn exchange user list & hzn exchange node create -n $HZN_EXCHANGE_NODE_AUTH

Did not work until I updated ./horizon/hzn.json with my own org id  (as explained in https://github.com/open-horizon/examples/blob/master/edge/services/helloworld/README.md#process-for-the-horizon-development-team-to-make-updates-to-the-helloworld-service )
"HZN_ORG_ID": "IBM",
To:
"HZN_ORG_ID": "bmtutor@us.ibm.com",

4.4. For node registration, hzn register -p IBM/pattern-ibm.helloworld
Make sure HZN_EXCHANGE_URL is set correctly (prod or staging -- as explained in https://github.com/open-horizon/examples/blob/master/edge/services/helloworld/README.md#process-for-the-horizon-development-team-to-make-updates-to-the-helloworld-service )
4.5 You can also check available patterns for ‘IBM/*’ with
hzn exchange pattern list 'IBM/*'

[
"IBM/pattern-bp.esstest-amd64",
"IBM/pattern-ibm.helloworld-amd64",
"IBM/pattern-ibm.helloworld",
"IBM/sdr2msghub",
"IBM/pattern-ibm.cpu2msghub-arm",
"IBM/pattern-ibm.cpu2msghub",
"IBM/cpu2msghub"
]

And use the -- help or -v flags for additional debugging / help information

5. Section “First-Time Edge Service Developer - Building and Publishing Your Own Version of the Hello World Edge Service”

5.1 but by modifying DOCKER_IMAGE_BASE “in horizon/hzn.json” you can store it in another registry.


5.2
Login to the docker registry using your id “and password (Note: replace mydockerpw with your password and mydockerhubid with your Docker hub id)”:

echo 'mydockerpw' | docker login -u mydockehubid --password-stdin

**Comment by jiportilla** [comment]
CPU2MSGHUB feedback from Development documentation:

CPU2MSGHUB Feedback


1.
Update Open-Horizon Examples repo link from
https://github.com/open-horizon
to:
https://github.com/open-horizon/examples

2. 
User may need sudo access to install git, make, jq

apt install -y git make jq 

3.
(As listed earlier for helloworld example)

3 Dockerfile.* variants for 3 different hardware architectures
To
Three Dockerfile.* variants for three different hardware architectures

4.
and the simpler, "hello" examples is that
to:
and the simpler, "helloworld" example is that …. 

5.
Update link to cpu2msghub README.MD file
https://github.com/open-horizon/examples/blob/master/edge/services/helloworld/README.md#first-time-edge-service-developer---building-and-publishing-your-own-version-of-the-hello-world-edge-service
To:
https://github.com/open-horizon/examples/blob/master/edge/msghub/cpu2msghub/README.md

6.
In required services, JSON looks different now:

"requiredServices": [
        {
            "url": "ibm.cpu",
            "org": "IBM",
            "version": "[0.0.0,INFINITY)",
            "arch": "$ARCH"
        },
        {
            "url": "ibm.gps",
            "org": "IBM",
            "version": "[0.0.0,INFINITY)",
            "arch": "$ARCH"
        }
    ],

Instead of:

"requiredServices": [
        {
            "url": "github.com.open-horizon.examples.cpu",
            "org": "IBM",
            "version": "[0.0.0,INFINITY)",
            "arch": "$ARCH"
        },
        {
            "url": "github.com.open-horizon.examples.gps",
            "org": "IBM",
            "version": "[0.0.0,INFINITY)",
            "arch": "$ARCH"
        }
    ],

7.
(From earlier feedback document)

7.1
 ,and only the other Service that has "required" it will be on the same network.
To
 ,and only the other Service that has a "required" setting in it will be on the same network.

7.2
When an IBM Edge Node is registered and in an agreement,
When an IBM Edge Node is registered and is in an agreement

7.3
(e.g., when team mates are developing 
((e.g., when teammates are developing 

7.4
In Choose Another Example section
Remove 3 – cpu2msghub as reader just completed this section


8.
Slight differences in Configuration variables for:
"SAMPLE_INTERVAL": 2,
             "SAMPLE_SIZE": 5,
             "VERBOSE": "1"

new
        {
            "name": "SAMPLE_SIZE",
            "label": "the number of samples to read before calculating the average",
            "type": "int",
            "defaultValue": "5"
        },
        
        {
            "name": "SAMPLE_SIZE",
            "label": "the number of samples to read before calculating the average",
            "type": "int",
            "defaultValue": "6"
        },
        
        new
        {
            "name": "SAMPLE_INTERVAL",
            "label": "the number of seconds between samples",
            "type": "int",
            "defaultValue": "5"
        },
        
        {
            "name": "SAMPLE_INTERVAL",
            "label": "the number of seconds between samples",
            "type": "int",
            "defaultValue": "2"
        },
        
             new
        {
            "name": "VERBOSE",
            "label": "log everything that happens",
            "type": "string",
            "defaultValue": "1"
        }
        {
            "name": "VERBOSE",
            "label": "log everything that happens",
            "type": "string",
            "defaultValue": "0"
        }

9.
horizon/userinput.json content is different from documentation:

{
    "services": [
        {
            "org": "$HZN_ORG_ID",
            "url": "$SERVICE_NAME",
            "variables": {
                "MOCK": false,
                "MSGHUB_API_KEY": "$MSGHUB_API_KEY",
                "MSGHUB_BROKER_URL": "$MSGHUB_BROKER_URL",
                "PUBLISH": true,
                "SAMPLE_INTERVAL": 2,
                "SAMPLE_SIZE": 5,
                "VERBOSE": "1"
            }
        }
    ]

Vs Online documentation:
{
    "services": [
        {
            "org": "IBM",
            "url": "ibm.cpu2msghub",
            "variables": {
                "MSGHUB_API_KEY": "$MSGHUB_API_KEY",
                "MSGHUB_TOPIC": "$MSGHUB_TOPIC",
                "MSGHUB_BROKER_URL": "$MSGHUB_BROKER_URL"
            }
        }
    ]
}

**Comment by jiportilla** [comment]
Feedback for cpu2msghub README.md 

Using the CPU To IBM Message Hub Edge Service Section:
1.
Add link to Try me section:
https://test.cloud.ibm.com/docs/edge-fabric?topic=edge-fabric-getting-started

2.
Add to development team instructions:

 update HZN_ORG_ID in horizon/hzn.json (otherwise ‘hzn exchange user list’ could fail)

3.
If “hzn exchange node confirm” fails, repeat node creation step
hzn exchange node create -n $HZN_EXCHANGE_NODE_AUTH with a different node id/pw

4.
Need access to a paid account to test: Missing MSGHUB_ADMIN_URL from welcome DM

curl -sS -w %{http_code} -H 'Content-Type: application/json' -H "X-Auth-Token: $MSGHUB_API_KEY" -d "{ \"name\": \"$MSGHUB_TOPIC\", \"partitions\": 2 }" $MSGHUB_ADMIN_URL/admin/topics

curl -sS -H "X-Auth-Token: $MSGHUB_API_KEY" $MSGHUB_ADMIN_URL/admin/topics | jq -r ".[] | .name"

kafkacat -C -q -o end -f "%t/%p/%o/%k: %s\n" -b $MSGHUB_BROKER_URL -X api.version.request=true -X security.protocol=sasl_ssl -X sasl.mechanisms=PLAIN -X sasl.username=${MSGHUB_API_KEY:0:16} -X sasl.password=${MSGHUB_API_KEY:16} -t $MSGHUB_TOPIC
% ERROR: Topic cpu2msghub error: Broker: Unknown topic or partition


First-Time Edge Service Developer - Building and Publishing Your Own Version of the CPU To IBM Message Hub Edge Service Section:


1.
Edit service.sh however you want, for example

json='{"nodeID":"'$HZN_DEVICE_ID'","cpu":'$average',"gps":'$loc'}'
To:
json='{"My-nodeID":"'$HZN_DEVICE_ID'","cpu":'$average',"gps":'$loc'}'

2. 404 errors

2. 
-make sure to login to docker & update horizon/hzn.json with your 
"DOCKER_IMAGE_BASE": "iportilla/ibm.cpu2msghub"

3.
hzn dev service start -S

Error: bad HTTP code 404 from GET https://stg.edge-fabric.com/v1/orgs/IBM/services?url=ibm.cpu&version=[0.0.0,INFINITY)&arch=amd64, output: {"services":{},"lastIndex":0}


4.

SERVICE_NAME not available for
Register your edge node with Horizon to use your deployment pattern (substitute for SERVICE_NAME the value you specified above for hzn dev service new -s):
Since:
Hzn dev service new -s was not issued above in this example

**Comment by jiportilla** [comment]
Feedback on testing in all three modes the examples found in the Development Guide

1.	As IBM Edge developer
2.	As Customer Service Developer
3.	As Customer user


1.. As IBM Edge Developer

1.
Make sure to update variables (like HZN_ORG_ID) in examples ./horizon/hzn.json with Edge Developer own values  
(as explained in: https://github.com/open-horizon/examples/blob/master/edge/services/helloworld/README.md#process-for-the-horizon-development-team-to-make-updates-to-the-helloworld-service )

2.
Define which environment will be used for testing (staging or production)
/etc/horizon/hzn.json
{
    "HZN_EXCHANGE_URL": " https://stg.edge-fabric.com/v1/",
    "HZN_FSS_CSSURL": " https://stg.edge-fabric.com/css /"
}

3.
Per earlier conversation in **slack, instructions for Edge developers should be remove from README.md in github and hosted somewhere else (box note?)
** we will make the `README.md` correct for soft GA now. It is time to focus only on soft GA. 



2.. As Customer Service Developer

Feedback provided earlier for helloworld and cpu2msghub examples.



3.. As Customer User 

1.
Differences in horizon versions

From hzn node list command:

"horizon_version": "2.23.1"

From documentation:

"horizon_version": "2.20.0"

2.
Regarding this statement: ‘You will also be provided (in a private message) ‘

Will clients get a private message in slack or an email?

3.
Regarding this statement:  ‘So in this case, please skip ahead to "Now that your Message Hub topic has been created and verified".’

These two variables $MSGHUB_TOPIC, $PATTERN will be blank

Since these steps will not be executed by skipping ahead.

 $ export PATTERN='IBM/cpu2msghub'
 $ export MSGHUB_TOPIC=`echo "$HZN_ORG_ID.$PATTERN" | sed 's;[@/];_;g'`
 $ echo $MSGHUB_TOPIC

4.
Create the following file and name it input.json

In other examples we call this file ‘userinput.json’, should we keep the same file name for consistency?

5.
The command:
hzn register -n $EXCHANGE_NODEAUTH $HZN_ORG_ID $PATTERN -f input.json

Will fail (per #3) since $PATTERN is undefined

6.
Is sudo needed to install kafkacat ?

apt install kafkacat

E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
