### ISSUE TITLE
Implement service development CI/CD process

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#174]
And document for customers.

**Comment by dcmartin** [comment]
An example CICD process for building services and patterns is described and implemented in the following repository, including sample services and patterns: https://github.com/dcmartin/open-horizon

**Comment by t-fine** [comment]
In regards to the issue I mentioned when trying to build and test on arm64 in the travis.yml file, I suppose this could be avoided (and perhaps should be) so that all the architectures build in the same "job" ...my thoughts are if they build in a separate job I don't yet know how I would figure out if the other architectures built successfully in their separate jobs, so that I can run publish-all-arches and use the `pattern-all-arches.json` file instead of having three different patterns for each arch in the exchange. 

So I think QEMU is the way to go for arm and arm64, not the build in cpu architecture options travis provides

**Comment by t-fine** [comment]
https://github.com/t-fine/examples/blob/master/.travis.yml

This is the current travis file I'm working on. It will test any changed services in a PR for all the arches it can run on (defined under a new `test-all-arches` target in the Makefile) noting all that passed, then publish those services and patters using a new `publish` Makefile target. 

Still need to work in IBM Event Streams monitoring for data publication from services. I originally thought this would require changes to the testing itself (serviceTest.sh), though I realized this does not work due to needing `EVTSTREAMS_*` environment variables. So this needs to happen in the travis file where the use of travis secrets can access the event streams credentials.
