### ISSUE TITLE
Links are broken on https://github.com/open-horizon/examples/wiki

### ISSUE THREAD

**Issue by gitjps** [open-horizon/examples#211]
- [x] Updated links to point to Edge Computing Documentation in the IBM Knowledge Center

**Comment by bmpotter** [comment]
Troy,

Thx for updating the wiki links. In looking over the wiki, it looks like everything below (and including) the line "The above guides are based on this example code" is old and out of date. I think for now we should just remove it. I'd rather have less info than wrong info.

Also, the additional wiki pages listed on the right i don't think are necessary. Since you've changed the documentation of all of the services to be in their README.md, i think that is the natural place for people to find it and we don't need wiki pages to point to it.

If you agree with this, please go ahead and make those changes.
