### ISSUE TITLE
Update Cloud Container Registry page

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#250]
Glen said that the current instructions don't work because the container registry (CR) has dropped support for a cr-specific token:

```
ibmcloud cr token-add --description 'testpaivmodel' --non-expiring
Requesting a registry token...
FAILED
The creation of registry tokens is discontinued. For more information about how to use API keys to automate access to your namespaces, see: https://cloud.ibm.com/docs/services/Registry?topic=registry-registry_access
```

So i'd like you to work thru the process for each of these, and give rene doc updates:
- [x] Using api key with IBM Cloud CR
- [x] Using api key with ICP CR
- [x] Using api key with OCP and CloudPak Foundation

**Comment by t-fine** [comment]
You can put your service containers into the IBM private secure container registry instead of the public Docker Hub. For instance, if a software image includes assets that are not appropriate to include in a public registry, you can use a private Docker container registry like the IBM Cloud Container Registry where access is tightly controlled.

**Before you begin**

Ensure that you install and use the IBM Cloud CLI tool. For more information about how to install the tool on many host hardware architectures and operating systems, see Installing the IBM Cloud CLI tool Opens in a new tab.

Using the IBM Cloud Container Registry 

1. Log in to the IBM Cloud by running the IBM Cloud CLI login command:
```
ibmcloud login --apikey <your-iamapikey>
```

2. Configure your organization. When you are logged in to the IBM Cloud, you need to configure your organization ID and space names that you want to use with the IBM Cloud CLI tool. Run the following command to configure these values:
```
ibmcloud target -o <org ID> -s <space ID>
```
For example:
```
ibmcloud target -o myorg@myorg.com -s mynamespace
```
If you do not know your organization ID and space name, use a web browser to log in to the IBM Cloud at the following URL: https://cloud.ibm.com/  Within IBM Cloud, you can find your organization ID and space. If you do not have an organization and space, you can create the values to use the container registry.

3. Create your private namespace. Use the ibmcloud cr command to create a private namespace in the IBM Cloud Container Registry under your account:
```
ibmcloud cr namespace-add <your namespace name>
```
For example:
```
ibmcloud cr namespace-add mynamespace
```

4. Log in to your Docker registry namespace by running the following command:
```
 ibmcloud cr login
```
For more information on using the ibmcloud cr command, see ibmcloud cr CLI web documentation . Additionally, you can run the command to view the help information:
```
 ibmcloud cr --help
```
After you log in to your private namespace in the IBM Cloud Container Registry. You do not need to use docker login to log in to the registry. You are now able to use container registry paths like the following path within yourdocker push and docker pull commands:
```
 us.icr.io/<namespace>/<image>_<arch>:<version>
```
For example:
```
 docker push us.icr.io/mynamespace/your-container_arch:1.2.3
```

5. Build and publish your images.
Log in to the IBM Cloud Container Registry.
Build your Docker images based on your preferences and name the images with the following form:
```
us.icr.io/<namespace>/<image>_<arch>:<version>
```
 3. Prefix your container name with the architecture for which your container was built.
```
  docker build -t us.icr.io/your-name_amd64:1.2.3 -f ./Dockerfile.amd64 .
  docker push us.icr.io/myamespace/your-name_amd64:1.2.3
```
 4. When your container is ready to be published, push the container to your private container registry, and publish the container to Horizon exchange. Use the following hzn command to push and publish your container:
```
  hzn exchange service publish -r "us.icr.io:iamapikey:<your-iamapikey>" -f service.definition.json

```
The -r "us.icr.io:iamapikey:<your-iamapikey>" argument indicates to Horizon which Docker container registry to use, and indicates your credentials, such as your API key.

The command completes the following tasks:
Push the Docker images to your IBM Cloud Container Registry, and get the digest of the image in the process.
Sign the digest and the deployment information with your private key.
Put the service metadata (including the signature) into Horizon exchange.
Put your public key into Horizon exchange under the service definition so Horizon edge nodes can automatically retrieve the definition to verify your signatures when needed.
Put your IBM Cloud Container Registry iamapikey into Horizon exchange under the service definition so Horizon edge nodes can automatically retrieve the definition when needed.

**Comment by t-fine** [comment]
Using The OCP Image Registry 

cloudctl login ...

export OCP_DOCKER_HOST=`oc get route default-route -n openshift-image-registry --template='{{ .spec.host }}’`

docker login -u kubeadmin -p $(oc whoami -t) $OCP_DOCKER_HOST

docker build -t $OCP_DOCKER_HOST/default/troy.helloworld_amd64:1.0.0 -f ./Dockerfile.amd64 .

docker push $OCP_DOCKER_HOST/default/troy.helloworld_amd64:1.0.0

**Comment by t-fine** [comment]
A few fixes to the page
--------------------------------------------

- I think we should actually delete the **Before you begin** section, and just move the small sentence or two at the top of each section on the different container registries 

Using the OCP image registry
---------------------------------------------------
If not already completed, you might need to manually **Expose the Registry** ( **LINK**: https://app.zenhub.com/workspaces/open-horizon-5877f2c6a8ad090f31c73853/issues/open-horizon/examples/250 ).

You will need the IBM Cloud Pak CLI and OpenShift Client CLI installed to complete the step in this section.


Using the IBM Cloud container registry
---------------------------------------------------
Ensure that you install and use the IBM Cloud CLI tool.


Using the IBM Cloud Private Container Registry <--- need to fix this heading of the third set of steps
---------------------------------------------------
Ensure that you install and use the IBM Cloud Pak CLI tool.
Note: This task requires Cluster administrator or team administrator user type or access level.

under this section, in the **"On the Linux operating system:"** section the code for steps 3 and 4 need to be fixed:

3. On your computer, create a directory to store the Docker registry certificate.
```
mkdir /etc/docker/certs.d/<cluster_CA_domain>:8500/
```
 
4. From the client machine (Linux® operating system) secure a copy of the registry certificate from the master node of your IBM Cloud Private cluster. The `<user>` in the following command is the user who has sudo permissions.
```
scp <user>@<cluster_CA_domain>:/etc/docker/certs.d/<cluster_CA_domain>\:8500/ca.crt /etc/docker/certs.d/<cluster_CA_domain>\:8500/ca.crt
```

**Comment by bmpotter** [comment]
I verified this process and made some adjustments to the documentation
