### ISSUE TITLE
Example edge cluster service with Operator

### ISSUE THREAD

**Issue by dabooz** [open-horizon/examples#310]
Initial material here:
https://ibm.ent.box.com/notes/622995576630 for creating an operator
We will need more material describing the hzn side.
We need both a sample and the doc on how to create the sample.

**Comment by t-fine** [comment]
KC doc on how to create a kibe operator:
https://ibm.ent.box.com/notes/658454881571

Will review for help with this task

**Comment by t-fine** [comment]
**Using an operator to deploy Hello World**
---------------------------------------------------

In order to deploy a containerized edge service to an edge cluster, a software developer first has to build a Kubernetes Operator that deploys the containerized edge service in a Kubernetes cluster. In the following example you will learn more about writing operators and how to deploy an edge service to a cluster (in this case `ibm.helloworld`), and learn how you can pass horizon environment variables (in addition to any other environment variables needed) to your deployed service pods.

See **Using an operator to deploy Hello World (LINK:** https://github.com/t-fine/examples/tree/operator-service/edge/services/operator)

**Comment by Rene-Ch1** [comment]
I incorporated the K content and sent to Troy (links prob don't work yet). https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.1/devices/developing/creating_hello_world.html
