### ISSUE TITLE
[BUG] edgeNodeFiles.sh -r option still attempts to run ocp registry commands

### ISSUE THREAD

**Issue by omega2733** [open-horizon/examples#324]
Description: When running the "-r" option within edgeNodeFiles.sh to use a non-ocp image registry commands are still run to obtain openshift registry information that we declared to not use, this results in a failed script run. Currently the docker login, docker pull, docker save (lines 355-387) are part of a function ``getImageFromOcpRegistry()`` which should be broken out into their own function so that a non-docker image registry can be used without script modification (especially if the oc console is not installed as this script will fail).

Solution: Breaking the docker commands out into their own function would allow the docker commands to run for any image registry and prevent from running openshift specific commands when -r is specified. When specifying -r in the new format we could skip ``getImageFromOCPRegistry()`` and only run the appropriate docker commands in the new function.

We probably would also want to somewhat decouple the cert gathering (324-333) so we can run this with both functions as it can run without the oc cli installed as well.

**Comment by LiilyZhang** [comment]
@omega2733 The requirement is we **always** pull agent image from management hub image registry, no matter if user uses their edge cluster registry or management hub image registry. 

For this issue, I will remove the supporting`-r` option for now. Since using edge cluster registry is "mandatory" at this point of time, no `-r` option will minimize the confusion of choosing image registry. After the change, `USE_EDGE_CLUSTER_REGISTRY` in agent-install.cfg will always be `true`

`-r` supporting will be bring back once agent image is able to pull directly by deployment.yml from management hub image registry

**Comment by bmpotter** [comment]
i've verified this
