### ISSUE TITLE
Return to multi-tenancy arch - talk about examples 

### ISSUE THREAD

**Issue by t-fine** [open-horizon/examples#356]
When we move back to multi-tenant architecture we should have a brief conversation on what do in the examples repo for the deployment policy/pattern files and if we want to leave `"public": true` in the `examples` repo in case anyone grabs their files from there when they create their own services and forgets to change that to `"public": false` making their services visible to people outside of their org.

**Comment by t-fine** [comment]
Conversation with Glen:

Hey Troy, we are going to move forward to re-enable multi-tenancy soon (e.g., so multiple companies could share a single management hub, and to each of them it would appear that they are alone on the management hub). When we do, do you think the examples should change to using "public": false? I’m mentioning this because I am thinking people would typically copy an example service.defintion.json file, and not notice this field, and then publish their service. If so and if the examples are "public": true then they would inadvertently make their services visible to other tenants. On the other hand, they would not be able to use the IBM services in their own patterns (but maybe nobody does that anyway)?

Hey Glen, oh awesome! Hmm yeah I guess that does bring up interesting problem... while I don't believe people really end up using the IBM published services them in their "real" services, they definitely use them to learn about services, policies, and patterns. I can't recall back to when we were on alpha, if there's two orgs and services with "public": false  does that mean I can't even list them with hzn exchange service list ORG/ ? Because there can't be "public": true patterns or deployment policies outside the IBM org so they still couldn't use them at least... (edited) 

Correct. To each org it appears they are the only users, except for things tagged "public": true. I think it would be best if all the IBM-published items were still "public": true in every Exchange, but the open-horizon/examples files they were built from would all change to "public": false. That would be a hassle to implement I guess, but I think that would be the best of both worlds.

**Comment by bmpotter** [comment]
Yes, when the examples are published in the `IBM` org they need to be public. And yes, our instructions to users on how to create examples should result in them creating `public:false` patterns and services by default. That could either be done having the instructions tell them to change the `public` field (and teaching them about that in the process), or they could be `public:false` in the repo and have `exchangePublishScript.sh` switch them to `public:true` right before publishing them in the `IBM` org.

Note that the [hello world instructions](https://github.com/open-horizon/examples/blob/master/edge/services/helloworld/CreateService.md#build-publish-your-hw) have them use `hzn dev service new` which creates the pattern with `public:false`, but for some reason creates the service with `public:true`. That should be changed.

**Comment by bmpotter** [comment]
I saw @clementkng 's PR 399, and i think that approach is a little clunky. I would prefer this approach:

- remove the `public` field from all of the examples
- modify `hzn exchange service publish` to add a flag that sets the public field to true or false. If the service metadata doesn't have the `public` field, this will add it before sending it to the exchange. If the service metadata **does** have the `public` field, this will override it.
- if this flag is not specified, it will use the public field that's in the metadata. If the public field isn't in the metadata, hzn will default it to false.

With this capability, we can remove the `public` field from all of the examples, and then `exchangePublish.sh` can set the flag when publishing them. I like this approach better, because the `public` field is more dynamic than the rest of the service metadata. The rest of the metadata is tightly tied to the service image implementation. The `public` field is affected more by the context in which you want to use it

**Comment by clementkng** [comment]
Hi @bmpotter it sounds like the approach you are suggesting would give the `hzn exchange service publish` the largest priority in determining the `public` field. Based on that, should we also make changes to hzn commands that set the `public` field to a value by default, like the aforementioned `hzn dev service new` command?

**Comment by bmpotter** [comment]
@clementkng , yes `hzn exchange service publish` is the first thing that needs to be changed. Let's name the new flag `--public=true` (or false). Not sure what single letter should be used for this, since `-p` and -`P` are both already taken.

To be clear, here's the `hzn exchange service publish` behavior for each case:
- public not set in the flag or metadata: set it to false
- the `public` field is set in the metadata:
    - if `--public=<bool>` is not specified, use the value in the metadata
    - if `--public=<bool>` is specified, use that value, regardless of what is in the metadata

We also have to roll this change out such that the examples will continue to work for both old and new users. I think we will be fine with this, because `exchangePublish.sh` uses the branch of the examples repo that is the same as the `hzn` version. (So for 4.2 users `v2.7`). We just have to document in the README's that when they are copying an example to create their own edge service, they should use the branch of the examples repo that is the same as the `hzn` version. (This should be part of this PR.)

**Comment by clementkng** [comment]
@bmpotter should I try to modify `hzn dev service new` command to not return any `public` field? Or do you think the changes to `hzn exchange service publish` should be sufficient?

**Comment by clementkng** [comment]
@t-fine I think this issue can be closed now. We have modified `hzn dev service new` to return a `public` field of false by default [here](https://github.com/open-horizon/anax/pull/2204).
